from fuze.errors.fuze_error import FuzeError